version: "3.1"

services:
    keycloak-database:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=1234
            - POSTGRES_DB=keycloak-react-db
        networks:
            - postgresql
    keycloak:
        image: jboss/keycloak:latest
        restart: always
        ports:
            - "4300:8080"
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - DB_VENDOR=postgres
            - DB_ADDR=keycloak-database
            - DB_DATABASE=keycloak-react-db
            - DB_USER=postgres
            - DB_PASSWORD=1234
        networks:
            - postgresql
        depends_on:
            - keycloak-database
networks:
    postgresql:
        driver: bridge
volumes:
    postgres: